<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="dsubhrajyoti" ignored="1" name="Default test" tests="1" failures="1" timestamp="04 Jul 2020 17:09:46 GMT" time="55.496" errors="0">
  <testcase name="verifyUseCaseTwo" time="36.863" classname="com.qa.test.TestScript.MyStoreTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Product Price failed to match expected [true] but found [false],
	Product quantity failed to match expected [true] but found [false],
	Product attribute failed to match expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Product Price failed to match expected [true] but found [false],
Product quantity failed to match expected [true] but found [false],
Product attribute failed to match expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.qa.test.pages.MyStorePage.verifyRightProductAddedToTheCartWithDiscount(MyStorePage.java:221)
at com.qa.test.pages.MyStorePage.verifyTheNumberOfItemsHavingDiscounts(MyStorePage.java:231)
at com.qa.test.TestScript.MyStoreTest.verifyUseCaseTwo(MyStoreTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyUseCaseTwo -->
  <testcase name="verifyUseCaseOne" time="0.0" classname="com.qa.test.TestScript.MyStoreTest">
    <ignored/>
  </testcase> <!-- verifyUseCaseOne -->
</testsuite> <!-- Default test -->
